apiVersion: v2
name: tenant
version: 2.2.1
description: Generic chart for provisioning tenant resources when using Argo CD Agent architecture
type: application
kubeVersion: '>=1.32.1'
sources:
 - https://github.com/gnunn-gitops/tenant-chart
maintainers:
- name: Gerald Nunn
