tenant: product-catalog

default:
    argocd:
      cluster: https://kubernetes.default.svc
    annotations:
      app.openshift.io/vcs-uri: https://github.com/gnunn-gitops/product-catalog
      app.openshift.io/vcs-ref: main
    labels:
      argocd.argoproj.io/managed-by: gitops
      tenant: product-catalog
    networkPolicy: true
    rbac:
      adminGroups:
        - product-catalog-admins
      editGroups:
        - product-catalog-users

argocd:
  namespace: gitops

namespaces:

  dev:
    quota: medium
    annotations:
      app.openshift.io/vcs-uri: https://github.com/gnunn-gitops/product-catalog
      app.openshift.io/vcs-ref: main

  test:
    quota: medium
    annotations:
      openshift.io/description: Project for test environment of product catalog application
      openshift.io/display-name: Product Catalog Test

  prod:
    quota: medium
    annotations:
      openshift.io/description: Project for production environment of product catalog application
      openshift.io/display-name: Product Catalog Prod

  cicd:
    annotations:
      openshift.io/description: Project for ci/cd tools for product catalog application
      openshift.io/display-name: Product Catalog CI/CD

  gitops:
    gitops: true
    annotations:
      openshift.io/description: Project for gitops tool for product catalog team
      openshift.io/display-name: Product Catalog GitOps

  monitor:
    annotations:
      openshift.io/description: Project for monitoring tools of product catalog application
      openshift.io/display-name: Product Catalog Monitor
    operatorGroup: true
