{{- if .Values.acs }}
{{- if eq .Values.acs.cluster .Values.cluster }}

{{- $destinations := list -}}
{{- range $k, $v := $.Values.namespaces }}
  {{- $destinations = append $destinations (ternary .destination $.Values.default.destination (hasKey . "destination")) }}
{{- end }}

{{- $uniqueDestinations := $destinations | uniq }}

{{- $tenantReadableName :=  .Values.tenant | replace "-" " " | title }}

apiVersion: v1
kind: Secret
metadata:
  name: declarative-configurations-{{ .Values.tenant }}
  namespace: rhacs-operator
type: Opaque
stringData:
  {{ .Values.tenant }}-access-scope.yaml: |
    name: {{ $tenantReadableName }}
    description: Access rights for users that can manage {{ .Values.tenant }} namespaces
    rules:
      included:
        {{- range $cluster := $uniqueDestinations }}
        - cluster: {{ $cluster }}
          namespaces:
        {{- range $k, $v := $.Values.namespaces }}
        {{- $namespace := printf "%s-%s" $.Values.tenant $k }}
        {{- $destination := ternary $v.destination $.Values.default.destination (hasKey $v "destination") }}
        {{- if eq $destination $cluster }}
            - {{ $namespace }}
        {{- end}}
        {{- end}}
        {{- end}}
  {{ .Values.tenant }}-roles.yaml: |
    name: {{ $tenantReadableName }}
    description: Administrators of {{ .Values.tenant }} namespaces
    permissionSet: Namespace Administrator
    accessScope: {{ $tenantReadableName }}
{{- end }}
{{- end }}
