{{- if and $.Values.argocd $.Values.argocd.namespace}}
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ $.Values.tenant }}
  namespace: {{ $.Values.argocd.namespace }}
  labels:
    argocd.argoproj.io/project-inherit: global
spec:
  description: {{ $.Values.tenant }} project
  destinations:
{{- range $k, $v := .Values.namespaces }}
{{- $namespace := printf "%s-%s" $.Values.tenant $k }}
  - namespace: '{{ $namespace }}'
{{- if and $v.argocd $v.argocd.cluster}}
    server: '{{ $v.argocd.cluster }}'
{{- else if and $.Values.default.argocd $.Values.default.argocd.cluster}}
    server: '{{ $.Values.default.argocd.cluster }}'
{{- end}}
{{- end}}
  sourceRepos:
  - '*'
  sourceNamespaces:
  - product-catalog-gitops
  roles:
    - description: {{ $.Values.tenant }} admins
      name: admin
      groups:
        - {{ $.Values.tenant }}-admins
      policies:
        - p, proj:{{ $.Values.tenant }}:admin, applications, *, {{ $.Values.tenant }}/*, allow
        - p, proj:{{ $.Values.tenant }}:admin, exec, create, {{ $.Values.tenant }}/*, allow
    - description: {{ $.Values.tenant }} users
      name: user
      groups:
        - {{ $.Values.tenant }}-users
      policies:
        - p, proj:{{ $.Values.tenant }}:user, applications, get, {{ $.Values.tenant }}/*, allow
        - p, proj:{{ $.Values.tenant }}:user, applications, sync, {{ $.Values.tenant }}/*, allow
    - description: Pipeline accounts
      name: pipeline
      groups:
        - {{ $.Values.tenant }}-pipeline
      policies:
        - p, proj:{{ $.Values.tenant }}:pipeline, applications, get, {{ $.Values.tenant }}/*, allow
        - p, proj:{{ $.Values.tenant }}:pipeline, applications, sync, {{ $.Values.tenant }}/*, allow
{{- end }}
