{{- if and $.Values.argocd $.Values.argocd.namespace}}
{{- range $k, $v := .Values.namespaces }}
{{- if $v.gitops }}
{{- $namespace := printf "%s-%s" $.Values.tenant $k }}
apiVersion: argoproj.io/v1beta1
kind: ArgoCD
metadata:
  name: argocd
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true,Validate=false
spec:
  sourceNamespaces:
    - {{ $namespace}}
{{- end }}
{{- end }}
{{- end }}
