{{- if $.Values.externalSecrets }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $.Values.tenant }}
  namespace: tenant-secrets
spec:
  data:
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: {{ $.Values.externalSecrets.tenantTokenKey }}
      metadataPolicy: None
    secretKey: eso-token
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ $.Values.externalSecrets.tenantClusterSecretStore }}
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      metadata:
        labels:
          replicate: "true"
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: {{ $.Values.tenant }}
spec:
  conditions:
  - namespaces:
      {{- range $k, $v := .Values.namespaces }}
      {{- $namespace := printf "%s-%s" $.Values.tenant $k }}
      - {{ $namespace }}
      {{- end}}
  provider:
    doppler:
      auth:
        secretRef:
          dopplerToken:
            key: eso-token
            name: {{ $.Values.tenant }}
            namespace: tenant-secrets
{{- end}}
