{{- range $k, $v := .Values.namespaces }}
{{- $namespace := printf "%s-%s" $.Values.tenant $k }}
---
apiVersion: v1
kind: Namespace
metadata:
{{- $labelData := dict "namespace" $v "values" $.Values }}
{{- include "merge-labels" $labelData }}
{{- $annotationData := dict "namespace" $v "values" $.Values }}
{{- include "merge-annotations" $annotationData }}
  name: {{ $namespace }}
---
{{- end }}
