{{- range $k, $v := .Values.namespaces }}
---
apiVersion: v1
kind: Namespace
metadata:
{{- $labelData := dict "namespace" $v "values" $.Values }}
{{- include "merge-labels" $labelData }}
{{- $annotationData := dict "namespace" $v "values" $.Values }}
{{- include "merge-annotations" $annotationData }}
  name: {{ $.Values.tenant }}-{{ $k }}
---
{{- end }}
