{{- range $k, $v := .Values.namespaces }}
{{- $size := $v.quota | default $.Values.default.quota }}
{{- $namespace := printf "%s-%s" $.Values.tenant $k }}
{{- if eq $size "small" }}
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota
  namespace: {{ $namespace }}
spec:
  hard:
    requests.cpu: "2"
    requests.memory: "1Gi"
    limits.memory: "2Gi"
---
apiVersion: "v1"
kind: "LimitRange"
metadata:
  name: limitrange
  namespace: {{ $namespace }}
spec:
  limits:
    - type: "Container"
      default:
        memory: "384Mi"
      defaultRequest:
        cpu: "100m"
        memory: "256Mi"
{{- else if eq $size "medium" }}
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota
  namespace: {{ $namespace }}
spec:
  hard:
    requests.cpu: "4"
    requests.memory: "2Gi"
    limits.memory: "4Gi"
---
apiVersion: "v1"
kind: "LimitRange"
metadata:
  name: limitrange
  namespace: {{ $namespace }}
spec:
  limits:
    - type: "Container"
      default:
        memory: "512Mi"
      defaultRequest:
        cpu: "200m"
        memory: "256Mi"
{{- else if eq $size "large" }}
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota
  namespace: {{ $namespace }}
spec:
  hard:
    requests.cpu: "8"
    requests.memory: "4Gi"
    limits.memory: "8Gi"
---
apiVersion: "v1"
kind: "LimitRange"
metadata:
  name: limitrange
  namespace: {{ $namespace }}
spec:
  limits:
    - type: "Container"
      default:
        memory: "512Mi"
      defaultRequest:
        cpu: "200m"
        memory: "256Mi"
{{- end}}
{{- end}}
