{{- if $.Values.externalSecrets }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ $.Values.tenant }}
  namespace: tenant-secrets
spec:
  data:
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: {{ $.Values.externalSecrets.tokenKey }}
      metadataPolicy: None
    secretKey: eso-token
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: tenants-token
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      metadata:
        labels:
          replicate: "true"
---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ $.Values.tenant }}
spec:
  conditions:
    - namespaceSelector:
        matchLabels:
          tenant: {{ $.Values.tenant }}
  provider:
    doppler:
      auth:
        secretRef:
          dopplerToken:
            key: eso-token
            name: {{ $.Values.tenant }}
            namespace: tenant-secrets
{{- end}}
